### ISSUE TITLE
Items to complete before first milestone release

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/cluster-capacity#68]
Focus the tool on its primary use-case around simulated scheduling decisions in preparation for an initial milestone release candidate.

**Must dos**

- [x] Remove the use of any unversioned clients as they represent support risks across Kubernetes releases that were exposed in the rebase to k8s 1.6.

- [x] Drop support for `--admission-control` flag as it uses unversioned clients

- [x] Drop support for `--resource-mode` flag as it mandated running a mock API server with upstream admission controllers that are operating against unversioned APIs.  Scheduler moved to versioned objects, and so this dichotomy exposed issues in the underlying caches that drive this simulator tool.  It is not safe, practical, or required to have `ResourceQuota` awareness in an initial milestone.

- [x] Make clear the output from `-o yaml|json` flag is not versioned/stable/guaranteed across releases.

- [x] Drop support for `--period` flag.  This flag causes the tool to run a server that can be interacted via curl and do "continuous cluster capacity analysis".  The API exposed needs more iteration, and running a server like this opens the risk of escalation style scenarios.  This can be explored in a future iteration, but its not required to reach an initial milestone.

- [x] Document `genpod` as an internal tool to the project.  User can provide their own sample pods to drive simulation behavior without growing the support space of tools offered by this project in its first iteration.

- [ ] Drop `--verbose` option in favor of a `-q` flag.  If -q is provided, just output the number of pods that can be scheduled, but not the individual failure reasons per node.  This will give us stable scripting against the CLI invocation.

- [x] Update documentation to reflect above

- [ ] Cut branch

- [ ] Push an image

**Comment by aveshagarwal** [comment]
Looks good.

**Comment by aveshagarwal** [comment]
I have addressed some tasks in https://github.com/kubernetes-incubator/cluster-capacity/pull/69.
 
2 additional item I have addressed in this PR is to update rebase from kube 1.6 rc1 to kube 1.6.  and also updated genpod to use versioned objects.

@derekwaynecarr in case you have looked into any item, please let me. I will look into remaining items tomorrow.

**Comment by derekwaynecarr** [comment]
I have not had time to look at any of remaining items.  I assume you are all set unless I hear otherwise.
